add_newline = false
format = "$directory$git_branch$git_status$character"

[directory]
style = "blue"
truncation_length = 3

[git_branch]
style = "purple"
format = "[$branch]($style) "

[git_status]
style = "red"
format = "[$all_status$ahead_behind]($style) "
conflicted = "conflict "
ahead = "ahead:${count} "
behind = "behind:${count} "
diverged = "ahead:${ahead_count} behind:${behind_count} "
untracked = "untracked:${count} "
stashed = "stashed "
modified = "modified:${count} "
staged = "staged:${count} "
renamed = "renamed:${count} "
deleted = "deleted:${count} "

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
