set -g prefix C-s
unbind C-b
bind C-s send-prefix

set -g mouse on
set -g default-terminal "tmux-256color"
setw -g mode-keys vi
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

set -ag terminal-overrides ",xterm-256color:RGB"

set -g status-position top
set -g pane-border-lines simple
set -g status-left ""
set -g window-status-format "•"
set -g window-status-current-format "•"
set -g pane-border-style "fg=#625e5a"
set -g pane-active-border-style "fg=#c4b28a"
set -g status-style "bg=default,fg=#c5c9c5"
set -g status-right "#[fg=#c4b28a]#S"
set -g window-status-style "fg=#625e5a"
set -g window-status-current-style "#{?window_zoomed_flag,fg=#e6c384,fg=#c4b28a,nobold}"
set -g window-status-bell-style "fg=#c4746e,nobold"

bind -r H resize-pane -L 5
bind -r L resize-pane -R 5

bind -n C-Tab next-window
bind -n C-S-Tab previous-window

bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'
