# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_FONTS
font_family      family="MesloLGL Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# Font size
font_size 16.0

# Cursor style
cursor_trail 1 

# Transparent background
dynamic_background_opacity yes
background_opacity 0.9
backgroundblur = 32

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
